/**
 * Deployment-package generator for the panel the app ships (see shared/panels.ts).
 *
 * Every file below is derived from the catalog entry — repository, port, panel
 * path, health path, data volume and env-var names — so switching the catalog to
 * a different panel (or renaming ours) changes the generated docker-compose.yml,
 * nginx.conf, .env, Dockerfile, railway.env, README and deploy.sh with it. No
 * panel-specific string is hardcoded here any more.
 *
 * The wizard calls these for the "download a ZIP" paths; the automated paths use
 * worker/railway.ts and worker/render.ts, which read the same catalog.
 */
import { buildPanelDeployEnv, panelDataDir, panelRepoUrl, panelTcpPorts, resolvePanel, type PanelSpec } from '../../shared/panels'

export interface VpsDeployConfig {
  name: string
  uuid: string
  adminPassword?: string
  domain?: string
  port?: string
  /** Catalog panel id — defaults to the first-party panel. */
  panel?: string
}

const panelOf = (cfg: VpsDeployConfig): PanelSpec => resolvePanel(cfg.panel)
const portOf = (cfg: VpsDeployConfig, p: PanelSpec) => cfg.port || String(p.port)
const healthOf = (p: PanelSpec) => p.healthPath ?? p.panelPath
const dataPathOf = panelDataDir
/** Container/service slug used by the generated compose + nginx. */
const serviceOf = (p: PanelSpec) => p.id

export function generateDockerCompose(cfg: VpsDeployConfig): string {
  const p = panelOf(cfg)
  const port = portOf(cfg, p)
  const svc = serviceOf(p)
  const name = cfg.name || svc
  const extra = (p.extraPorts ?? []).map((n) => `\n      - "${n}:${n}"`).join('')
  const caps = (p.capAdd ?? []).length ? `\n    cap_add:\n${p.capAdd!.map((c) => `      - ${c}`).join('\n')}` : ''
  return `# miliconfig — ${p.name} Docker Deployment
# Generated by miliconfigpro panel
#
# The image is built from the project's own Dockerfile (see deploy.sh, which
# clones ${p.repo} into ./${svc}-src first), so the panel and its xray-core
# runtime always match the upstream release.

services:
  ${svc}:
    build: ./${svc}-src
    container_name: ${name}
    restart: unless-stopped
    env_file: .env
    ports:
      - "${port}:${port}"${extra}
    volumes:
      - ./${svc}-data:${dataPathOf(p)}${caps}
    healthcheck:
      test: ["CMD", "python", "-c", "import os,urllib.request; urllib.request.urlopen('http://127.0.0.1:'+os.getenv('PORT','${port}')+'${healthOf(p)}',timeout=3)"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  nginx:
    image: nginx:alpine
    container_name: ${name}-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - ${svc}
    command: "/bin/sh -c 'nginx -g \\"daemon off;\\"'"

  certbot:
    image: certbot/certbot
    container_name: ${name}-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait; certbot renew; done;'"
    profiles:
      - certonly
`
}

export function generateNginxConf(cfg: VpsDeployConfig): string {
  const p = panelOf(cfg)
  const domain = cfg.domain || '_'
  const svc = serviceOf(p)
  const port = portOf(cfg, p)
  return `# miliconfig — ${p.name} nginx reverse proxy
events {
    worker_connections 1024;
}

http {
    upstream ${svc} {
        server ${svc}:${port};
    }

    server {
        listen 80;
        server_name ${domain};

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            proxy_pass http://${svc};
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # WebSocket support (required by the proxy transports)
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 86400;
        }
    }

    # HTTPS server (uncomment after the first certbot run)
    # server {
    #     listen 443 ssl http2;
    #     server_name ${domain};
    #
    #     ssl_certificate /etc/letsencrypt/live/${domain}/fullchain.pem;
    #     ssl_certificate_key /etc/letsencrypt/live/${domain}/privkey.pem;
    #
    #     location / {
    #         proxy_pass http://${svc};
    #         proxy_set_header Host $host;
    #         proxy_set_header X-Real-IP $remote_addr;
    #         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #         proxy_set_header X-Forwarded-Proto $scheme;
    #         proxy_http_version 1.1;
    #         proxy_set_header Upgrade $http_upgrade;
    #         proxy_set_header Connection "upgrade";
    #         proxy_read_timeout 86400;
    #     }
    # }
}
`
}

export function generateEnvFile(cfg: VpsDeployConfig): string {
  const p = panelOf(cfg)
  const manifest = buildPanelDeployEnv(p, 'vps', {
    adminPassword: cfg.adminPassword || 'changeme',
    secretKey: cfg.uuid,
    publicBaseUrl: cfg.domain ? `https://${cfg.domain}` : undefined,
    directHost: cfg.domain,
  })
  return `# miliconfig — ${p.name} environment
${manifest.map((item) => `${item.name}=${item.value}`).join('\n')}\n`
}

// ── Railway deployment ────────────────────────────────────────────────────────

/**
 * The Railway *variable* manifest, as a file the operator can paste.
 *
 * This is the half of a Railway deployment the repository cannot ship for us:
 * upstream already has a `Dockerfile` and a `railway.json`, and they are the
 * only correct ones — the repository's image is what installs the engines the
 * panel actually runs, and its `railway.json` is the deploy config the project
 * tests against. Copying a hand-rolled pair over them in a fork replaces the
 * real ones with a stale subset, so the package carries no Dockerfile and no
 * Railway config at all; what is left is the part only this installation can
 * know: its own generated secrets and the variable names its panel reads.
 *
 * The two values only the operator has are named in the header and left blank
 * on purpose — a wrong project id is worse than none, because the panel's
 * TCP-proxy pass would then fail with an authorization error that looks like a
 * bad token.
 */
export function generateRailwayEnvFile(cfg: VpsDeployConfig): string {
  const p = panelOf(cfg)
  const manifest = buildPanelDeployEnv(p, 'railway', {
    adminPassword: cfg.adminPassword || cfg.uuid || 'changeme',
    secretKey: cfg.uuid,
    publicBaseUrl: cfg.domain ? `https://${cfg.domain}` : undefined,
    railwayProjectId: '',
  })
  const lines = manifest.filter((item) => item.value !== '').map((item) => `${item.name}=${item.value}`)
  return `# miliconfig — ${p.name} Railway variables
# Paste these into Railway → your service → Variables.
#
# ${p.env.railwayProjectId ?? 'NEXUS_RAILWAY_PROJECT_ID'} — the id in your project's dashboard URL
#   (railway.com/project/<id>). Railway injects the environment and the service
#   id into every deployment but never the project id, and the panel's own
#   TCP-proxy pass does not run without it — so without this the panel can never
#   publish a raw-TCP port.
# ${p.env.railwayToken ?? 'NEXUS_RAILWAY_TOKEN'} — a Project Token for this project.
#   The panel uses it to create one TCP proxy per raw port you switch on.
#
# Railway mounts its volume as root while the panel's image runs as an
# unprivileged user, so without this it cannot create its SQLite file and
# crash-loops on boot.
RAILWAY_RUN_UID=0

${lines.join('\n')}
`
}

export function generateRailwayReadme(cfg: VpsDeployConfig): string {
  const p = panelOf(cfg)
  const pw = cfg.adminPassword || cfg.uuid || 'changeme'
  const dataPath = dataPathOf(p)
  const manifest = buildPanelDeployEnv(p, 'railway', {
    adminPassword: pw,
    secretKey: cfg.uuid,
  })
  return `# ${cfg.name} — ${p.name} Railway Deployment

## One-click deploy

1. Fork ${p.url} to your GitHub
2. Go to https://railway.app/new
3. Click **Deploy from GitHub repo** → select the forked repo
4. Railway reads the repository's own railway.json (Dockerfile builder, the
   ${healthOf(p)} healthcheck, restart on failure). **Do not add a Dockerfile or a
   railway.json of your own** — the repository's image is the only one that
   installs every engine the panel runs, and its config is the one the project
   tests against.
5. In **Settings → Variables**, set:

   | Variable | Value |
   |----------|-------|
${manifest.map((item) => `   | \`${item.name}\` | \`${item.value || '(empty)' }\` |`).join('\n')}

6. Add a **Volume** mounted at \`${dataPath}\` — without it the panel's database
   does not survive a redeploy
7. In **Settings → Networking** click **Generate Domain**. Railway publishes HTTPS
   only, so every raw-TCP listener needs its own TCP proxy whose public port
   Railway allocates at random — the panel creates those itself, one per
   capability you switch on, and shows you the port it was given. It cannot do
   that without NEXUS_RAILWAY_TOKEN and NEXUS_RAILWAY_PROJECT_ID (step 8 and the
   variable table).

The raw-TCP listeners, in the order a client should try them — Reality is the
one this deployment publishes for you, the rest appear once you enable them in
the panel:
${panelTcpPorts(p).map((t) => `   - \`${t.port}\` — ${t.label}`).join('\n')}

8. Create a Project Token in project settings, and read the project id off the
   dashboard URL (railway.com/project/<id>); set the project id as
   NEXUS_RAILWAY_PROJECT_ID and the token as
   \`${p.env.railwayToken ?? 'NEXUS_RAILWAY_TOKEN'}\`; enable GitHub Auto Deploy for \`main\`

## Panel access

- URL: https://your-app.up.railway.app${p.panelPath}
- Username: \`admin\` · Password: \`${pw}\`

## Files in this package

| File | Purpose |
|------|--------|
| railway.env | The variables to paste into Railway |

---
Generated by miliconfigpro panel
`
}

export function generateDeployScript(cfg: VpsDeployConfig): string {
  const p = panelOf(cfg)
  const svc = serviceOf(p)
  const port = portOf(cfg, p)
  return `#!/bin/bash
# miliconfig — ${p.name} one-click deploy
# Run this on your VPS: bash deploy.sh

set -e

echo "🚀 Deploying ${p.name}..."
echo ""

# 1. Create directories
mkdir -p ${svc}-src ${svc}-data certbot/conf certbot/www

# 2. Clone the panel source (its own Dockerfile builds the image)
echo "📥 Cloning ${p.repo}..."
rm -rf ${svc}-src/*
git clone --depth 1 ${panelRepoUrl(p)} ${svc}-src

# 3. Start services
echo "🐳 Starting Docker containers..."
docker compose up -d --build

echo ""
echo "✅ ${p.name} is running!"
echo "   Panel: http://YOUR_SERVER_IP:${port}${p.panelPath}"
echo "   Admin: admin / ${cfg.adminPassword || 'changeme'}"
echo ""
echo "Set up HTTPS:"
echo "  1. Point your domain DNS to this server"
echo "  2. Set the public URL in .env"
echo "  3. Run: docker compose --profile certonly run --rm certbot certonly --webroot -w /var/www/certbot -d your.domain.com"
echo "  4. Uncomment the HTTPS server block in nginx.conf"
echo "  5. Run: docker compose restart nginx"
`
}
