/**
 * Deployment-package generator for the panel the app ships (see shared/panels.ts).
 *
 * Every file below is derived from the catalog entry — repository, port, panel
 * path, health path, data volume and env-var names — so switching the catalog to
 * a different panel (or renaming ours) changes the generated docker-compose.yml,
 * nginx.conf, .env, Dockerfile, railway.toml, README and deploy.sh with it. No
 * panel-specific string is hardcoded here any more.
 *
 * The wizard calls these for the "download a ZIP" paths; the automated paths use
 * worker/railway.ts and worker/render.ts, which read the same catalog.
 */
import { panelDataDir, panelDataFile, panelRepoUrl, resolvePanel, type PanelSpec } from '../../shared/panels'

export interface VpsDeployConfig {
  name: string
  uuid: string
  adminPassword?: string
  domain?: string
  port?: string
  /** Catalog panel id — defaults to the first-party panel. */
  panel?: string
}

const panelOf = (cfg: VpsDeployConfig): PanelSpec => resolvePanel(cfg.panel)
const portOf = (cfg: VpsDeployConfig, p: PanelSpec) => cfg.port || String(p.port)
const healthOf = (p: PanelSpec) => p.healthPath ?? p.panelPath
const dataPathOf = panelDataDir
/** Container/service slug used by the generated compose + nginx. */
const serviceOf = (p: PanelSpec) => p.id

export function generateDockerCompose(cfg: VpsDeployConfig): string {
  const p = panelOf(cfg)
  const port = portOf(cfg, p)
  const svc = serviceOf(p)
  const name = cfg.name || svc
  const extra = (p.extraPorts ?? []).map((n) => `\n      - "${n}:${n}"`).join('')
  const caps = (p.capAdd ?? []).length ? `\n    cap_add:\n${p.capAdd!.map((c) => `      - ${c}`).join('\n')}` : ''
  return `# miliconfig — ${p.name} Docker Deployment
# Generated by miliconfigpro panel
#
# The image is built from the project's own Dockerfile (see deploy.sh, which
# clones ${p.repo} into ./${svc}-src first), so the panel and its xray-core
# runtime always match the upstream release.

services:
  ${svc}:
    build: ./${svc}-src
    container_name: ${name}
    restart: unless-stopped
    env_file: .env
    ports:
      - "${port}:${port}"${extra}
    volumes:
      - ./${svc}-data:${dataPathOf(p)}${caps}
    healthcheck:
      test: ["CMD", "python", "-c", "import os,urllib.request; urllib.request.urlopen('http://127.0.0.1:'+os.getenv('PORT','${port}')+'${healthOf(p)}',timeout=3)"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  nginx:
    image: nginx:alpine
    container_name: ${name}-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - ${svc}
    command: "/bin/sh -c 'nginx -g \\"daemon off;\\"'"

  certbot:
    image: certbot/certbot
    container_name: ${name}-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait; certbot renew; done;'"
    profiles:
      - certonly
`
}

export function generateNginxConf(cfg: VpsDeployConfig): string {
  const p = panelOf(cfg)
  const domain = cfg.domain || '_'
  const svc = serviceOf(p)
  const port = portOf(cfg, p)
  return `# miliconfig — ${p.name} nginx reverse proxy
events {
    worker_connections 1024;
}

http {
    upstream ${svc} {
        server ${svc}:${port};
    }

    server {
        listen 80;
        server_name ${domain};

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            proxy_pass http://${svc};
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # WebSocket support (required by the proxy transports)
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 86400;
        }
    }

    # HTTPS server (uncomment after the first certbot run)
    # server {
    #     listen 443 ssl http2;
    #     server_name ${domain};
    #
    #     ssl_certificate /etc/letsencrypt/live/${domain}/fullchain.pem;
    #     ssl_certificate_key /etc/letsencrypt/live/${domain}/privkey.pem;
    #
    #     location / {
    #         proxy_pass http://${svc};
    #         proxy_set_header Host $host;
    #         proxy_set_header X-Real-IP $remote_addr;
    #         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #         proxy_set_header X-Forwarded-Proto $scheme;
    #         proxy_http_version 1.1;
    #         proxy_set_header Upgrade $http_upgrade;
    #         proxy_set_header Connection "upgrade";
    #         proxy_read_timeout 86400;
    #     }
    # }
}
`
}

export function generateEnvFile(cfg: VpsDeployConfig): string {
  const p = panelOf(cfg)
  const port = portOf(cfg, p)
  const admin = cfg.adminPassword || 'changeme'
  const secret = cfg.uuid
  const extra = (p.extraPorts ?? []).length ? `NEXUS_DIRECT_PORT=${p.extraPorts![0]}\n` : ''
  return `# miliconfig — ${p.name} environment
${p.env.adminPassword ?? 'ADMIN_PASSWORD'}=${admin}
${p.env.secretKey ?? 'SECRET_KEY'}=${secret}
${p.env.port ?? 'PORT'}=${port}
${p.env.dataDir ?? 'SQLITE_PATH'}=${panelDataFile(p)}
${p.env.publicDomain ?? 'PUBLIC_BASE_URL'}=${cfg.domain ? `https://${cfg.domain}` : ''}
XRAY_ENABLED=1
NEXUS_PLATFORM=vps
${extra}`
}

// ── Railway deployment ────────────────────────────────────────────────────────

/** Generated Dockerfile: mirrors the project's own image (xray + the app). */
export function generateRailwayDockerfile(cfg: VpsDeployConfig): string {
  const p = panelOf(cfg)
  const pw = cfg.adminPassword || cfg.uuid || 'changeme'
  const port = portOf(cfg, p)
  return `# miliconfig — ${p.name} Railway Deployment
# Same shape as the project's own Dockerfile: the official xray-core binary plus
# the panel, cloned at build time.

FROM ghcr.io/xtls/xray-core:26.9.9 AS xray
FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1 PIP_DISABLE_PIP_VERSION_CHECK=1
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends git && rm -rf /var/lib/apt/lists/*

RUN git clone --depth 1 ${panelRepoUrl(p)} /app

RUN pip install --no-cache-dir -r requirements.txt

COPY --from=xray /usr/local/bin/xray /usr/local/bin/xray

RUN mkdir -p ${dataPathOf(p)}

ENV ${p.env.adminPassword ?? 'ADMIN_PASSWORD'}=${pw}
ENV ${p.env.secretKey ?? 'JWT_SECRET'}=${cfg.uuid}
ENV ${p.env.port ?? 'PORT'}=${port}
ENV XRAY_ENABLED=1
ENV NEXUS_PLATFORM=railway

EXPOSE ${port}

CMD ["sh", "-c", "exec uvicorn app.main:app --host 0.0.0.0 --port \${PORT:-${port}} --proxy-headers --forwarded-allow-ips='*'"]`
}

export function generateRailwayToml(cfg: VpsDeployConfig): string {
  const p = panelOf(cfg)
  const pw = cfg.adminPassword || cfg.uuid || 'changeme'
  const port = portOf(cfg, p)
  return `# miliconfig — Railway deploy config for ${p.name}
# Generated by miliconfigpro panel

[build]
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh -c 'exec uvicorn app.main:app --host 0.0.0.0 --port \${PORT:-${port}} --proxy-headers --forwarded-allow-ips=*'"
healthcheckPath = "${healthOf(p)}"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[deploy.env]
${p.env.adminPassword ?? 'ADMIN_PASSWORD'} = "${pw}"
${p.env.secretKey ?? 'JWT_SECRET'} = "${cfg.uuid}"
${p.env.port ?? 'PORT'} = "${port}"
XRAY_ENABLED = "1"
NEXUS_PLATFORM = "railway"
`
}

export function generateRailwayReadme(cfg: VpsDeployConfig): string {
  const p = panelOf(cfg)
  const pw = cfg.adminPassword || cfg.uuid || 'changeme'
  const port = portOf(cfg, p)
  const dataPath = dataPathOf(p)
  return `# ${cfg.name} — ${p.name} Railway Deployment

## One-click deploy

1. Fork ${p.url} to your GitHub
2. Go to https://railway.app/new
3. Click **Deploy from GitHub repo** → select the forked repo
4. Railway auto-detects the Dockerfile and deploys
5. In **Settings → Variables**, set:

   | Variable | Value |
   |----------|-------|
   | ${p.env.adminPassword ?? 'ADMIN_PASSWORD'} | \`${pw}\` |
   | ${p.env.secretKey ?? 'JWT_SECRET'} | \`${cfg.uuid}\` |
   | ${p.env.port ?? 'PORT'} | \`${port}\` |

6. Add a **Volume** mounted at \`${dataPath}\` — without it the panel's database
   does not survive a redeploy
7. In **Settings → Networking**, click **Generate Domain**

## Panel access

- URL: https://your-app.up.railway.app${p.panelPath}
- Username: \`admin\` · Password: \`${pw}\`

## Files in this package

| File | Purpose |
|------|--------|
| Dockerfile | Builds ${p.name} with xray-core |
| railway.toml | Railway deploy configuration |

---
Generated by miliconfigpro panel
`
}

export function generateDeployScript(cfg: VpsDeployConfig): string {
  const p = panelOf(cfg)
  const svc = serviceOf(p)
  const port = portOf(cfg, p)
  return `#!/bin/bash
# miliconfig — ${p.name} one-click deploy
# Run this on your VPS: bash deploy.sh

set -e

echo "🚀 Deploying ${p.name}..."
echo ""

# 1. Create directories
mkdir -p ${svc}-src ${svc}-data certbot/conf certbot/www

# 2. Clone the panel source (its own Dockerfile builds the image)
echo "📥 Cloning ${p.repo}..."
rm -rf ${svc}-src/*
git clone --depth 1 ${panelRepoUrl(p)} ${svc}-src

# 3. Start services
echo "🐳 Starting Docker containers..."
docker compose up -d --build

echo ""
echo "✅ ${p.name} is running!"
echo "   Panel: http://YOUR_SERVER_IP:${port}${p.panelPath}"
echo "   Admin: admin / ${cfg.adminPassword || 'changeme'}"
echo ""
echo "Set up HTTPS:"
echo "  1. Point your domain DNS to this server"
echo "  2. Set the public URL in .env"
echo "  3. Run: docker compose --profile certonly run --rm certbot certonly --webroot -w /var/www/certbot -d your.domain.com"
echo "  4. Uncomment the HTTPS server block in nginx.conf"
echo "  5. Run: docker compose restart nginx"
`
}
